name: laptop
bert_mapper: activebus/BERT-DK_laptop
sbert_mapper: all-mpnet-base-v2

aspect_category_mapper: ['support', 'os', 'display', 'battery', 'company', 'mouse', 'software', 'keyboard']
aspect_seed_mapper:
        'support': ["support", "service", "warranty", "coverage", "replace"]
        'os': ["os", "windows", "ios", "mac", "system", "linux"]
        'display': ["display", "screen", "led", "monitor", "resolution"]
        'battery': ["battery", "life", "charge", "last", "power"]
        'company': ["company", "product", "hp", "toshiba", "dell", "apple", "lenovo"]
        'mouse': ["mouse", "touch", "track", "button", "pad"]
        'software': ["software", "programs", "applications", "itunes", "photo"]
        'keyboard': ["keyboard", "key", "space", "type", "keys"]

sentiment_category_mapper: ['negative', 'positive']
sentiment_seed_mapper:
        positive: ["good", "great", 'nice', "excellent", "perfect"]
        negative: ["bad", "terrible", "horrible", "disappointed ", "awful"]

validation_data_size: 150
hyper_validation_size: 0.8

cat_threshold: 0.5
pol_threshold: 0.3

N: 9

params:
        learning_rate: 1e-6
        beta1: 0.99
        beta2: 0.97
        batch_size: 18
        gamma1: 4
        gamma2: 4