name: restaurant-5
bert_mapper: activebus/BERT-DK_rest
sbert_mapper: all-mpnet-base-v2

aspect_category_mapper: ['location', 'drinks', 'food', 'ambience', 'service']
aspect_seed_mapper:
        location: ["location", "street", "block", "river", "avenue"]
        drinks: ["drinks", "beverage", "wines", "margaritas", "sake"]
        food: ["food", "spicy", "sushi", "pizza", "taste"]
        ambience: ["ambience", "atmosphere", "room", "seating", "environment"]
        service: ["service", "tips", "manager", "waitress", "servers"]

sentiment_category_mapper: ['negative', 'positive']
sentiment_seed_mapper:
        positive: ["good", "great", 'nice', "excellent", "perfect"]
        negative: ["bad", "terrible", "horrible", "disappointed ", "awful"]

validation_data_size: 100
hyper_validation_size: 0.8

cat_threshold: 0.55
pol_threshold: 0.5

# CASC specific parameters
N: 5
M: 100
aspect_weights: [5, 25, 345, 67, 201]
sentiment_weights: [231, 382]

params:
        learning_rate: 1e-6
        beta1: 0.95
        beta2: 0.97
        batch_size: 24
        gamma1: 4
        gamma2: 4