name: supermarket
bert_mapper: /dbfs/FileStore/kto/kto/BERT-DK_kto
sbert_mapper: paraphrase-multilingual-mpnet-base-v2

aspect_category_mapper: ['service', 'assortiment', 'beschikbaarheid', 'corona', 'kwaliteit', 'winkel', 'personeel', 'opgeruimd', 'prijzen', 'overig']
aspect_seed_mapper:
  service: ["scanner", "zelfscan", "afrekenen", "kassa", "service"]
  assortiment: ["assortiment", "aanbod", "biologische", "vegan"]
  beschikbaarheid: ["beschikbaarheid", "uitverkocht", "voorraad", "verkrijgbaar", "leeg"]
  corona: ["corona", "covid", "mondkapje", "desinfecteren", "coronamaatregelen"]
  kwaliteit: ["vers", "kwaliteit", "rot", "beschimmeld", "houdbaarheid"]
  winkel: ["garage", "smal", "indeling", "toilet", "ruimte"]
  personeel: ["klantvriendelijk", "begroeten", "vriendelijk", "hulp", "personeel", "vakkenvullers"]
  opgeruimd: ["rommelig", "smerig", "afval", "vies", "opruimen"]
  prijzen: ["prijs", "duur", "goedkoper", "35%"]
  overig: ["duurzaam", "bloemen", "bezorgen", "reeds", "vermeld", "enquete"]

sentiment_category_mapper: ['negative', 'positive']
sentiment_seed_mapper:
  positive: ["goed", "geweldig", 'uitstekend', "excellent", "perfect"]
  negative: ["slecht", "verschrikkelijk", "afgrijselijk", "teleurgesteld ", "vreselijk"]

validation_data_size: 150
hyper_validation_size: 0.8

cat_threshold: 0.7
pol_threshold: 0.4

# CASC specific parameters
N: 9
M: 150
aspect_weights: [11, 81, 62, 23, 10, 118, 43, 19, 6, 8]
sentiment_weights: [208, 173]

params:
  learning_rate: 1e-4
  beta1: 0.9
  beta2: 0.92
  batch_size: 12
  gamma1: 4
  gamma2: 4