device: cuda
epochs: 15
defaults:
  - _self_
  - domain: restaurant3
  - model: SBASC
  - environment: local
  - optional domain_model: ${domain}_${model}

path_mapper: ${data_path}${domain.name}
result_path_mapper: ${result_path}${domain.name}