# @package _global_
domain:
  cat_threshold: 0.7
  pol_threshold: 0.6

  aspect_seed_mapper:
    location: [
      "convenient location to my apartment .",
      "the views and surroundings were spectacular . ",
      "we had a tremendous view of the river .",
      "located at the end of a magnificent block .",
      "the outdoor atmosphere of sitting on the sidewalk watching the world go by 50 feet away on 6th avenue on a cool evening was wonderful ."
    ]
    food: [
      "the food is good",
      "this is the best sushi buffet we ever had ",
      "all the dishes tasted the same .",
      "the pizza at old chicago is actually pretty good",
      "hamburgers bland and buns dry and cold .",
      #"the tacos were so delicious that when i started eating , i texted my husband to go there on his way home from work .",
    ]
    drinks: [
      "the drinks were amazing as well , my husband and i will definitely be coming back !",
      "they also have nice selection of beverages like fresh teas and lemonade .",
      "the wine list was pretty extensive and had nice , good wines .",
      "really bad margaritas !",
      "asahi bombers for $ 5- $ 6 -- they also have delicious plum sake ."
    ]
    ambience: [
      "great place to chill and enjoy some alone time with a cool ambience about the place !",
      #"butterfields is a great environment and atmosphere with waffles on the ceiling , great neighborhood",
      "seating is limited-call ahead for a large group . decor is updated and modern-will definitely be back again and again ",
      "this place is a total dump .",
      "spacious booths and tables that do n't feel cramped .",
      "the atmosphere at toast was very warm and comfortable",
    ]
    service: [
      "the owner and staff are very friendly and communicative",
      "our server was rude , slow and snapped her fingers when we needed water # # # refills",
      "the service was extremely good as our water cups rarely ran low and the manager was very helpful in getting the bill comped .",
      "and the service is by far the worst i 've ever experienced",
      #"the service is very good and the servers are very nice . i brought my sorority sisters to celebrate a bachelorette and the food was served quickly .",
      "the waitresses were friendly and attentive to our questions/comments .",
    ]

  sentiment_seed_mapper:
    positive: [
      "service was great",
      "every bite was super tender and the bun was nice and fresh",
      "friendly staff and warm ambiance",
      "we also ordered pita and hummus and that was delicious",
      "i really loved everything about it",
      "decently priced food and fast delivery",
      "fast delivery and terrific food",
      "very clean , great staff , good food",
      "this restaurant is clean with super friendly staff and awesome food"

    ]
    negative: [
      "i 'm sad to say i ca n't find anything positive to say about the experience",
      "the service over the past year is terrible",
      "any day of the week it 's bad",
      "horrible food . wretched service . vastly overpriced . i would rather starve than eat here again .",
      "horrible , over priced food",
      "the service was awful",
      "food was awful , group of 16 and none of us were please , everything was either cold or tasteless , i almost believe it was from the awl-mart frozen section",
      "and our table was sticky and smelled of beer",
      "not the best experience with the foods . our hot foods were served cold",
      "service was slow"
    ]


  params:
    batch_size: 12
    beta1: 0.99
    beta2: 0.97
    gamma1: 4
    gamma2: 4
    learning_rate: 1e-6