# @package _global_
domain:
  cat_threshold: 0.75
  pol_threshold: 0.6

  aspect_seed_mapper:
    service: [
      "met de zelfscankassa heb ik slechte ervaringen",
      "zelfscan is erg fijn",
      "snelle afrekenen mogelijkheid",
      "na de verbouwing is het afrekenen echt een ergernis geworden , er zijn minder normale kassa , dus lange wachtrijen",
      "te lange rij bij de kassa"
    ]
    assortiment: [
      "een goed assortiment aan artikelen en veel keuze",
      "breed aanbod aan producten",
      "goed assortiment",
      "meer producten in de schappen",
      "albert heijn heeft veel vegan en bio mogelijkheden in hun assortiment" ]
    beschikbaarheid: [
      "beschikbaarheid van artikelen is zeer goed",
      "zorgen dat niet steeds veel artikelen uitverkocht zijn",
      "voorraad beter aanvullen",
      "bonus aanbiedingen zijn vaak niet ( meer ) voorradig",
      "veel vakken leeg" ]
    corona: [
      "winkel is niet corona veilig",
      "houden zich ook uitstekend aan de covid maatregelen",
      "mensen er op wijzen dat ze een mondkapje op moeten , dat dit mondkapje ook over de neus moet ",
      "zorgen dat je je handen kunt schoonmaken bij de ingang",
      "beter letten op de coronamaatregelen"
    ]
    kwaliteit: [
      "groente en fruit niet erg vers",
      "de kwaliteit van fruit en groente is nogal eens niet zo best zoals bij de kersen , sperziebonen etc .",
      "gekocht fruit is na enkele dagen rot .",
      "alweer beschimmelde groenten",
      "houdbaarheid beter in de gaten houden" ]
    winkel: [
      "fijne winkel",
      "het is gewoon een goede winkel",
      "ingang en buiten omgeving verbeteren ",
      "vooral het trappenhuis van de parkeergarage",
      "veel zwervers en afval voor de ingang",
      "parkeergarage is heel vervelend"
    ]
    personeel: [
      "vriendelijk personeel",
      "vriendelijk en behulpzaam personeel",
      "leidinggevenden zouden wel vriendelijker mogen zijn",
      "ik krijg altijd goede hulp bij vragen",
      "erg fijn en vriendelijk personeel in de winkel"
    ]
    opgeruimd: [
      "ik vind dat de winkel rommelig is vooral bij de voormalige vleeswaren afd ",
      "de winkel is niet netjes",
      "erg rommelig",
      "minder dozen in de paden",
      "deel groentenafdeling was vies" ]
    prijzen: [
      "betere kwaliteit prijs verhoudingen",
      "ah is nu eenmaal duur",
      "goedkoper worden .",
      "ik sta tevaak bij de service balie om 35 % korting te krijgen of omdat de kassabon niet klopt" ]
    overig: [
      "zou fijn zijn als jullie ook producten kunnen bezorgen",
      "reeds diverse malen aangegeven , maar er verandert niets",
      "reden is bekend , al vele malen opgegeven",
      "zie mijn vorige antwoorden",
      "ik doe geen aanbevelingen"
    ]

  sentiment_seed_mapper:
    positive: [
      "over het algemeen een erg goede supermarkt",
      "schone , ruime winkel met vriendelijk en behulpzaam personeel",
      'assortiment en personeel zijn uitstekend .',
      "goed winkel met een excellent medewerkers .",
      "ruim en goed assortiment"]
    negative: [
      "deze ah winkel onderscheidt zicht niet t.o.v . jumbo",
      "rommelig en slecht assortiment",
      "onvriendelijk personeel",
      "te klein aanbod aan producten",
      "ik ben teleurgesteld over de aanlevering van de voorraden "
    ]

  params:
    learning_rate: 1e-6
    beta1: 0.97
    beta2: 0.99
    batch_size: 12
    gamma1: 2
    gamma2: 2